name: OpenTelemetry

on:
  workflow_run:
    workflows: [Autorerun, Autoversion, CI, CodeQL, Copilot code review, Copilot coding agent, Publish, Renovate]
    types:
      - completed

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/workflow@v5.45.1
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
    permissions:
      actions: read
    container: ghcr.io/plengauer/opentelemetry-github-workflow-instrumentation-runner:v5.45.1
