name: OpenTelemetry

on:
  workflow_run:
    workflows: [Autoapprove, Autorerun, Autoversion, Publish, Renovate, Copilot coding agent]
    types:
      - completed

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/workflow@v5.42.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
    permissions:
      actions: read
